services:
  mysql:
    image: mysql:8.0
    container_name: mini-cafe-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mini_cafe
      MYSQL_USER: cafe_user
      MYSQL_PASSWORD: cafe123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mini-cafe-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: mini-cafe-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: cafe_user
      DB_PASSWORD: cafe123
      DB_NAME: mini_cafe
      JWT_SECRET: 413f5523001e34828a7a6c88dba392c050cca0814408817a6fd4660a465568f9cf7d8fcdf103d4c01eac4fdd00065005ab93dad6cd5939489308dd57ea51bbb0
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    container_name: mini-cafe-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json

volumes:
  mysql-data:
  backend-node-modules:
  frontend-node-modules:
